# Generated by Django 5.0 on 2023-12-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorApp', '0003_alter_historicalperfomance_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperfomance',
            name='average_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicalperfomance',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicalperfomance',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicalperfomance',
            name='quality_rating_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
